name: CI

permissions:
  contents: read

on:
  push:
    branches: ["main"]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install build tools
        run: sudo apt-get update && sudo apt-get install -y cmake build-essential libreadline-dev

      - name: Prepare build system
        run: cmake -B build -S .

      - name: Compile program
        run: cmake --build ./build

      - name: Upload build artifact
        uses: actions/upload-artifact@v7
        with:
          name: build
          path: build/kash

  test:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["pypy3.10", "3.9", "3.10", "3.11", "3.12", "3.13"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install testing tools
        run: python -m pip install -r requirements.txt

      - name: Download build artifact
        uses: actions/download-artifact@v8
        with:
          name: build
          path: build/

      - name: Make binary executable
        run: chmod +x build/kash

      - name: Run integration tests
        run: python -m pytest
